name: Generate Daily/Midday/Nightly Post

on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 14 * * *"
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup PNPM
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate post
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODELS_TOKEN: ${{ secrets.MODELS_TOKEN }}
        run: pnpm run generate

      - name: Commit and push new post
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: add digest"
          file_pattern: "src/content/posts/*.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
