name: Generate Daily/Midday/Nightly Post

on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 14 * * *"
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PNPM
        uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate post
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODELS_TOKEN: ${{ secrets.MODELS_TOKEN }}
        run: pnpm run generate

      - name: Commit and push new post
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore: add digest"
          file_pattern: "src/content/posts/*.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
